### PR TITLE
add arsenal gui hacks cuz why not

### PR DESCRIPTION
**Pull request by Volas171**

### CODE REVIEW

**Comment by Itzbenz** [comment]
how effective

**Comment by shadow01148** [comment]
gonna find 3, hold on

**Comment by shadow01148** [comment]
or 10 of them i guess

**Comment by Volas171** [comment]
pussy

**Comment by shadow01148** [comment]
wtf its closed

**Comment by Volas171** [comment]
yes

**Comment by Volas171** [comment]
sex

**Comment by shadow01148** [comment]
amazing

**Comment by shadow01148** [comment]
how to get member

**Comment by Volas171** [comment]
idk ask itzben or nexity

**Comment by shadow01148** [comment]
ok ok ok

**Comment by shadow01148** [comment]
sdgjslgjd

**Comment by shadow01148** [comment]
gang shit

**Pull request closed without merging**
